### PR TITLE
PHP code for faculty contact

### PR DESCRIPTION
**Pull request by arindammajee**
I have write the PHP code for displaying faculty contact. But the image portion is not working properly. First of all , the image is not moving to the 'uploads' folder but the image property is being saved in the Database. Otherwise all other details are properly working. I am working to fix the image portion . Help Needed.
Screenshot from 2020-05-13 20-55-12

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
Change the PR to the ayan/develop2 branch and not in master .
And have you checked the page is mobile comptatible or not

**Comment by arindammajee** [comment]
Screenshot from 2020-05-13 21-02-58
Yes. It is Mobile comptatible. Look at the screenshot. I have reduced the screen width for firefox and it's showing properly.

**Comment by ayan-biswas0412** [comment]
okk it's fine i will check and merge it very soon

**Comment by arindammajee** [comment]
Okay. Currently I am trying to fix the image problem.

**Comment by ayan-biswas0412** [comment]
@Arindam-coder your code works fine but provide the updated sql file because my screen is showing blank ...:)

**Comment by ayan-biswas0412** [comment]
just @Arindam-coder git add .  the updated sql file and commit again thats it , noo need to do any separate PR

@Arindam-coder There is also no input panel to maintain the faculty details inside the faculty dashboard

**Comment by ayan-biswas0412** [comment]
> Okay. Currently I am trying to fix the image problem.

okk no problem

**Comment by ayan-biswas0412** [comment]
@Arindam-coder export the full SQL with table data, there is no data exported in faculty _contact table 
Screenshot from 2020-05-13 21-39-30
and also this error is shown to me

**Comment by ayan-biswas0412** [comment]
Nice Work @Arindam-coder now just try to make a input panel for the input of the information of each faculty and store them agaist their id in faculty contact table and i am merging this , make a separate PR in this branch later

**Pull request merged**
